#!/bin/bash
# 
#curl "http://localhost:9000/computedescriptors?params=-2d|-3d|-dir|/home/mols|-file|/home/mols/$1"
curl "http://localhost:9001/computedescriptors?params=-2d|-3d|-dir|/home/oriol/dev/explorations/PaDEL-descriptor-ws/test_mols|-file|mols.txt"
